[2022-12-11 18:49:27,500] INFO | setup >>> App started...
[2022-12-11 18:49:27,505] INFO | _internal >>> [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.144.196:5000
[2022-12-11 18:49:27,505] INFO | _internal >>> [33mPress CTRL+C to quit[0m
[2022-12-11 18:49:38,431] INFO | engine >>> A user visited the home page >>> {'request_id': 'e2511075-1173-4f6b-9c3c-644bee6d2a9b'}
[2022-12-11 18:49:38,468] INFO | _internal >>> 127.0.0.1 - - [11/Dec/2022 18:49:38] "GET / HTTP/1.1" 200 -
[2022-12-11 18:49:38,554] INFO | _internal >>> 127.0.0.1 - - [11/Dec/2022 18:49:38] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2022-12-11 18:49:52,000] INFO | engine >>> A user visited the home page >>> {'request_id': 'dff170a4-4c63-4286-9e46-d8b5bdc50fce'}
[2022-12-11 18:49:52,002] INFO | _internal >>> 127.0.0.1 - - [11/Dec/2022 18:49:52] "[32mPOST / HTTP/1.1[0m" 302 -
[2022-12-11 18:49:52,016] INFO | engine >>> A user deleted the employee whose email address was ajeet1@gmail.com 
[2022-12-11 18:49:52,017] INFO | _internal >>> 127.0.0.1 - - [11/Dec/2022 18:49:52] "[32mGET /employee/delete/ajeet1%40gmail.com HTTP/1.1[0m" 302 -
[2022-12-11 18:49:52,028] INFO | engine >>> A user visited the home page >>> {'request_id': '4a886c65-2142-4b0e-8af6-8b11b57fc3f3'}
[2022-12-11 18:49:52,031] INFO | _internal >>> 127.0.0.1 - - [11/Dec/2022 18:49:52] "GET /employee HTTP/1.1" 200 -
[2022-12-11 18:49:52,059] INFO | _internal >>> 127.0.0.1 - - [11/Dec/2022 18:49:52] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2022-12-12 12:46:42,585] INFO | setup >>> App started...
[2022-12-12 12:46:42,595] INFO | _internal >>> [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.65.196:5000
[2022-12-12 12:46:42,596] INFO | _internal >>> [33mPress CTRL+C to quit[0m
[2022-12-12 12:47:00,266] INFO | _internal >>> 127.0.0.1 - - [12/Dec/2022 12:47:00] "[32mGET / HTTP/1.1[0m" 302 -
[2022-12-12 12:47:00,317] INFO | _internal >>> 127.0.0.1 - - [12/Dec/2022 12:47:00] "GET /auth/login HTTP/1.1" 200 -
[2022-12-12 12:47:00,432] INFO | _internal >>> 127.0.0.1 - - [12/Dec/2022 12:47:00] "GET /static/style.css HTTP/1.1" 200 -
[2022-12-12 12:47:00,559] INFO | _internal >>> 127.0.0.1 - - [12/Dec/2022 12:47:00] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[2022-12-12 12:47:02,029] INFO | _internal >>> 127.0.0.1 - - [12/Dec/2022 12:47:02] "[32mGET /employee/detail HTTP/1.1[0m" 302 -
[2022-12-12 12:47:02,046] INFO | _internal >>> 127.0.0.1 - - [12/Dec/2022 12:47:02] "GET /auth/login HTTP/1.1" 200 -
[2022-12-12 12:47:02,132] INFO | _internal >>> 127.0.0.1 - - [12/Dec/2022 12:47:02] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2022-12-12 12:47:03,187] INFO | _internal >>> 127.0.0.1 - - [12/Dec/2022 12:47:03] "GET /home HTTP/1.1" 200 -
[2022-12-12 12:47:03,253] INFO | _internal >>> 127.0.0.1 - - [12/Dec/2022 12:47:03] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2022-12-12 12:47:04,764] INFO | _internal >>> 127.0.0.1 - - [12/Dec/2022 12:47:04] "[32mGET /employee HTTP/1.1[0m" 302 -
[2022-12-12 12:47:04,770] INFO | _internal >>> 127.0.0.1 - - [12/Dec/2022 12:47:04] "GET /auth/login HTTP/1.1" 200 -
[2022-12-12 12:47:04,808] INFO | _internal >>> 127.0.0.1 - - [12/Dec/2022 12:47:04] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2022-12-12 12:47:17,652] INFO | _internal >>> 127.0.0.1 - - [12/Dec/2022 12:47:17] "[32mPOST /auth/login HTTP/1.1[0m" 302 -
[2022-12-12 12:47:17,662] INFO | engine >>> A user visited the home page >>> {'request_id': '9e45bbfd-677b-4cad-a4b7-68a2db112dd7'}
[2022-12-12 12:47:17,685] INFO | _internal >>> 127.0.0.1 - - [12/Dec/2022 12:47:17] "GET / HTTP/1.1" 200 -
[2022-12-12 12:47:17,747] INFO | _internal >>> 127.0.0.1 - - [12/Dec/2022 12:47:17] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2022-12-12 12:47:44,912] INFO | engine >>> A user visited the home page >>> {'request_id': 'dace6eee-bf84-4670-975a-d1b6ba4b30fc'}
[2022-12-12 12:47:44,915] INFO | _internal >>> 127.0.0.1 - - [12/Dec/2022 12:47:44] "[32mPOST / HTTP/1.1[0m" 302 -
[2022-12-12 12:47:44,931] INFO | _internal >>> 127.0.0.1 - - [12/Dec/2022 12:47:44] "GET /employee/update/nil10%40gmail.com HTTP/1.1" 200 -
[2022-12-12 12:47:44,966] INFO | _internal >>> 127.0.0.1 - - [12/Dec/2022 12:47:44] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2022-12-12 12:47:49,205] INFO | engine >>> A user updated the employee details >>> {'request_id': 'dace6eee-bf84-4670-975a-d1b6ba4b30fc'}
[2022-12-12 12:47:49,207] INFO | _internal >>> 127.0.0.1 - - [12/Dec/2022 12:47:49] "[32mPOST /employee/update/nil10%40gmail.com HTTP/1.1[0m" 302 -
[2022-12-12 12:47:49,225] INFO | _internal >>> 127.0.0.1 - - [12/Dec/2022 12:47:49] "[32mGET /auth/logout HTTP/1.1[0m" 302 -
[2022-12-12 12:47:49,240] INFO | _internal >>> 127.0.0.1 - - [12/Dec/2022 12:47:49] "[32mGET / HTTP/1.1[0m" 302 -
[2022-12-12 12:47:49,248] INFO | _internal >>> 127.0.0.1 - - [12/Dec/2022 12:47:49] "GET /auth/login HTTP/1.1" 200 -
[2022-12-12 12:47:49,294] INFO | _internal >>> 127.0.0.1 - - [12/Dec/2022 12:47:49] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2022-12-12 12:48:18,804] INFO | _internal >>> 127.0.0.1 - - [12/Dec/2022 12:48:18] "[32mPOST /auth/login HTTP/1.1[0m" 302 -
[2022-12-12 12:48:18,816] INFO | engine >>> A user visited the home page >>> {'request_id': 'f1129a29-3908-46e7-bac8-2ed744e148c0'}
[2022-12-12 12:48:18,821] INFO | _internal >>> 127.0.0.1 - - [12/Dec/2022 12:48:18] "GET / HTTP/1.1" 200 -
[2022-12-12 12:48:18,876] INFO | _internal >>> 127.0.0.1 - - [12/Dec/2022 12:48:18] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2022-12-12 12:48:25,976] INFO | _internal >>> 127.0.0.1 - - [12/Dec/2022 12:48:25] "GET /employee/detail HTTP/1.1" 200 -
[2022-12-12 12:48:26,013] INFO | _internal >>> 127.0.0.1 - - [12/Dec/2022 12:48:26] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2022-12-12 12:48:28,895] INFO | _internal >>> 127.0.0.1 - - [12/Dec/2022 12:48:28] "GET /auth/register HTTP/1.1" 200 -
[2022-12-12 12:48:28,987] INFO | _internal >>> 127.0.0.1 - - [12/Dec/2022 12:48:28] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2022-12-12 12:48:31,887] INFO | _internal >>> 127.0.0.1 - - [12/Dec/2022 12:48:31] "[32mGET /auth/logout HTTP/1.1[0m" 302 -
[2022-12-12 12:48:31,895] INFO | _internal >>> 127.0.0.1 - - [12/Dec/2022 12:48:31] "[32mGET / HTTP/1.1[0m" 302 -
[2022-12-12 12:48:31,903] INFO | _internal >>> 127.0.0.1 - - [12/Dec/2022 12:48:31] "GET /auth/login HTTP/1.1" 200 -
[2022-12-12 12:48:31,933] INFO | _internal >>> 127.0.0.1 - - [12/Dec/2022 12:48:31] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2022-12-14 10:48:30,331] INFO | setup >>> App started...
[2022-12-14 10:48:30,343] INFO | _internal >>> [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.245.196:5000
[2022-12-14 10:48:30,344] INFO | _internal >>> [33mPress CTRL+C to quit[0m
[2022-12-18 09:32:19,885] INFO | setup >>> App started...
[2022-12-18 09:32:19,893] INFO | _internal >>> [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.205.196:5000
[2022-12-18 09:32:19,895] INFO | _internal >>> [33mPress CTRL+C to quit[0m
[2022-12-18 09:32:32,268] INFO | _internal >>> 127.0.0.1 - - [18/Dec/2022 09:32:32] "GET /auth/login HTTP/1.1" 200 -
[2022-12-18 09:32:32,436] INFO | _internal >>> 127.0.0.1 - - [18/Dec/2022 09:32:32] "GET /static/style.css HTTP/1.1" 200 -
[2022-12-18 09:32:38,470] INFO | _internal >>> 127.0.0.1 - - [18/Dec/2022 09:32:38] "[32mPOST /auth/login HTTP/1.1[0m" 302 -
[2022-12-18 09:32:38,484] INFO | engine >>> A user visited the home page >>> {'empId': 6}
[2022-12-18 09:32:38,554] INFO | _internal >>> 127.0.0.1 - - [18/Dec/2022 09:32:38] "GET / HTTP/1.1" 200 -
[2022-12-18 09:32:38,599] INFO | _internal >>> 127.0.0.1 - - [18/Dec/2022 09:32:38] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2022-12-18 09:32:47,388] INFO | _internal >>> 127.0.0.1 - - [18/Dec/2022 09:32:47] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[2022-12-18 09:32:49,938] INFO | _internal >>> 127.0.0.1 - - [18/Dec/2022 09:32:49] "GET /employee/detail HTTP/1.1" 200 -
[2022-12-18 09:32:49,996] INFO | _internal >>> 127.0.0.1 - - [18/Dec/2022 09:32:49] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2022-12-18 09:33:28,394] INFO | _internal >>> 127.0.0.1 - - [18/Dec/2022 09:33:28] "GET /auth/register HTTP/1.1" 200 -
[2022-12-18 09:33:28,424] INFO | _internal >>> 127.0.0.1 - - [18/Dec/2022 09:33:28] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2022-12-18 09:34:23,017] DEBUG | connectionpool >>> Starting new HTTP connection (1): api:5001
[2022-12-18 09:34:27,748] ERROR | app >>> Exception on /auth/register [POST]
Traceback (most recent call last):
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\nileshtiwari\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Users\nileshtiwari\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\nileshtiwari\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\nileshtiwari\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\nileshtiwari\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Users\nileshtiwari\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001B232634880>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='api', port=5001): Max retries exceeded with url: http://127.0.0.1:5001/post (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B232634880>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "c:\Users\nileshtiwari\Desktop\AdvancedPython\flaskApp\auth.py", line 123, in register
    send_data_to_api_db(data_to_save_in_api_db)
  File "c:\Users\nileshtiwari\Desktop\AdvancedPython\flaskApp\auth.py", line 228, in send_data_to_api_db
    response = requests.post("http://127.0.0.1:5001/post",proxies={"http": "http://api:5001/post"}, verify=False,json=data,headers=headers)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\requests\adapters.py", line 559, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPConnectionPool(host='api', port=5001): Max retries exceeded with url: http://127.0.0.1:5001/post (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B232634880>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')))
[2022-12-18 09:34:27,963] INFO | _internal >>> 127.0.0.1 - - [18/Dec/2022 09:34:27] "[35m[1mPOST /auth/register HTTP/1.1[0m" 500 -
[2022-12-18 09:34:27,994] ERROR | _internal >>> Error on request:
Traceback (most recent call last):
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\nileshtiwari\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Users\nileshtiwari\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\nileshtiwari\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\nileshtiwari\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\nileshtiwari\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Users\nileshtiwari\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001B232634880>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='api', port=5001): Max retries exceeded with url: http://127.0.0.1:5001/post (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B232634880>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "c:\Users\nileshtiwari\Desktop\AdvancedPython\flaskApp\auth.py", line 123, in register
    send_data_to_api_db(data_to_save_in_api_db)
  File "c:\Users\nileshtiwari\Desktop\AdvancedPython\flaskApp\auth.py", line 228, in send_data_to_api_db
    response = requests.post("http://127.0.0.1:5001/post",proxies={"http": "http://api:5001/post"}, verify=False,json=data,headers=headers)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\requests\adapters.py", line 559, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPConnectionPool(host='api', port=5001): Max retries exceeded with url: http://127.0.0.1:5001/post (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B232634880>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\werkzeug\serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\werkzeug\serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\flask\app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\flask\app.py", line 1724, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
  File "c:\Users\nileshtiwari\Desktop\AdvancedPython\flaskApp\errors.py", line 11, in handle_500
    return render_template('errors/500.html'), 500
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "c:\Users\nileshtiwari\Desktop\AdvancedPython\flaskApp\templates\errors\500.html", line 8, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'.
[2022-12-18 09:38:25,797] INFO | engine >>> A user visited the home page >>> {'empId': 6}
[2022-12-18 09:38:25,806] INFO | _internal >>> 127.0.0.1 - - [18/Dec/2022 09:38:25] "GET / HTTP/1.1" 200 -
[2022-12-18 09:38:25,830] INFO | _internal >>> 127.0.0.1 - - [18/Dec/2022 09:38:25] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2022-12-18 09:38:31,238] INFO | engine >>> A user visited the home page >>> {'empId': 6}
[2022-12-18 09:38:31,244] INFO | _internal >>> 127.0.0.1 - - [18/Dec/2022 09:38:31] "[32mPOST / HTTP/1.1[0m" 302 -
[2022-12-18 09:38:31,290] INFO | _internal >>> 127.0.0.1 - - [18/Dec/2022 09:38:31] "GET /employee/update/anurag1%40gmail.com HTTP/1.1" 200 -
[2022-12-18 09:38:31,345] INFO | _internal >>> 127.0.0.1 - - [18/Dec/2022 09:38:31] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2022-12-18 09:38:35,354] DEBUG | connectionpool >>> Starting new HTTP connection (1): api:5001
[2022-12-18 09:38:40,113] ERROR | app >>> Exception on /employee/update/anurag1@gmail.com [POST]
Traceback (most recent call last):
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\nileshtiwari\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Users\nileshtiwari\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\nileshtiwari\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\nileshtiwari\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\nileshtiwari\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Users\nileshtiwari\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001B2326163E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='api', port=5001): Max retries exceeded with url: http://127.0.0.1:5001/update (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B2326163E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "c:\Users\nileshtiwari\Desktop\AdvancedPython\flaskApp\auth.py", line 37, in wrapped_view
    return view(**kwargs)
  File "c:\Users\nileshtiwari\Desktop\AdvancedPython\flaskApp\auth.py", line 48, in wrapped_view
    return view(**kwargs)
  File "c:\Users\nileshtiwari\Desktop\AdvancedPython\flaskApp\engine.py", line 112, in update
    update_api_db_data(data)
  File "c:\Users\nileshtiwari\Desktop\AdvancedPython\flaskApp\engine.py", line 202, in update_api_db_data
    response = requests.post("http://127.0.0.1:5001/update",proxies={"http": "http://api:5001/update"}, verify=False,json=data)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\requests\adapters.py", line 559, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPConnectionPool(host='api', port=5001): Max retries exceeded with url: http://127.0.0.1:5001/update (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B2326163E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')))
[2022-12-18 09:38:40,133] INFO | _internal >>> 127.0.0.1 - - [18/Dec/2022 09:38:40] "[35m[1mPOST /employee/update/anurag1%40gmail.com HTTP/1.1[0m" 500 -
[2022-12-18 09:38:40,137] ERROR | _internal >>> Error on request:
Traceback (most recent call last):
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\nileshtiwari\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Users\nileshtiwari\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\nileshtiwari\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\nileshtiwari\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\nileshtiwari\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Users\nileshtiwari\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001B2326163E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='api', port=5001): Max retries exceeded with url: http://127.0.0.1:5001/update (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B2326163E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "c:\Users\nileshtiwari\Desktop\AdvancedPython\flaskApp\auth.py", line 37, in wrapped_view
    return view(**kwargs)
  File "c:\Users\nileshtiwari\Desktop\AdvancedPython\flaskApp\auth.py", line 48, in wrapped_view
    return view(**kwargs)
  File "c:\Users\nileshtiwari\Desktop\AdvancedPython\flaskApp\engine.py", line 112, in update
    update_api_db_data(data)
  File "c:\Users\nileshtiwari\Desktop\AdvancedPython\flaskApp\engine.py", line 202, in update_api_db_data
    response = requests.post("http://127.0.0.1:5001/update",proxies={"http": "http://api:5001/update"}, verify=False,json=data)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\requests\adapters.py", line 559, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPConnectionPool(host='api', port=5001): Max retries exceeded with url: http://127.0.0.1:5001/update (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B2326163E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\werkzeug\serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\werkzeug\serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\flask\app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\flask\app.py", line 1724, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
  File "c:\Users\nileshtiwari\Desktop\AdvancedPython\flaskApp\errors.py", line 11, in handle_500
    return render_template('errors/500.html'), 500
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "c:\Users\nileshtiwari\Desktop\AdvancedPython\flaskApp\templates\errors\500.html", line 1, in top-level template code
    {% extends header.html %}
  File "C:\Users\nileshtiwari\Desktop\AdvancedPython\env\lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'header' is undefined
[2022-12-23 22:27:55,687] INFO | setup >>> App started...
[2022-12-23 22:27:55,696] INFO | _internal >>> [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.164.196:5000
[2022-12-23 22:27:55,698] INFO | _internal >>> [33mPress CTRL+C to quit[0m
[2022-12-23 22:28:02,284] INFO | _internal >>> 192.168.164.196 - - [23/Dec/2022 22:28:02] "[32mGET / HTTP/1.1[0m" 302 -
[2022-12-23 22:28:02,319] INFO | _internal >>> 192.168.164.196 - - [23/Dec/2022 22:28:02] "GET /auth/login HTTP/1.1" 200 -
[2022-12-23 22:28:02,419] INFO | _internal >>> 192.168.164.196 - - [23/Dec/2022 22:28:02] "GET /static/style.css HTTP/1.1" 200 -
[2022-12-23 22:28:06,795] INFO | _internal >>> 192.168.164.196 - - [23/Dec/2022 22:28:06] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[2022-12-23 22:28:29,531] INFO | _internal >>> 192.168.164.196 - - [23/Dec/2022 22:28:29] "[32mPOST /auth/login HTTP/1.1[0m" 302 -
[2022-12-23 22:28:29,542] INFO | engine >>> A user visited the home page >>> {'empId': 6}
[2022-12-23 22:28:29,568] INFO | _internal >>> 192.168.164.196 - - [23/Dec/2022 22:28:29] "GET / HTTP/1.1" 200 -
[2022-12-23 22:28:29,622] INFO | _internal >>> 192.168.164.196 - - [23/Dec/2022 22:28:29] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2022-12-29 19:50:04,071] INFO | setup >>> App started...
[2022-12-29 19:50:04,079] INFO | _internal >>> [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://127.0.0.1:5000
[2022-12-29 19:50:04,080] INFO | _internal >>> [33mPress CTRL+C to quit[0m
[2022-12-29 19:50:13,454] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:50:13] "[32mGET / HTTP/1.1[0m" 302 -
[2022-12-29 19:50:13,577] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:50:13] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 19:50:13,705] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:50:13] "GET /static/style.css HTTP/1.1" 200 -
[2022-12-29 19:50:13,718] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:50:13] "GET /static/alert.js HTTP/1.1" 200 -
[2022-12-29 19:50:13,895] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:50:13] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[2022-12-29 19:50:57,192] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:50:57] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 19:50:57,228] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:50:57] "GET /static/style.css HTTP/1.1" 200 -
[2022-12-29 19:50:57,239] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:50:57] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 19:51:04,839] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:51:04] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 19:51:04,873] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:51:04] "GET /static/style.css HTTP/1.1" 200 -
[2022-12-29 19:51:04,884] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:51:04] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 19:51:17,205] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:51:17] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 19:51:17,249] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:51:17] "GET /static/style.css HTTP/1.1" 200 -
[2022-12-29 19:51:17,255] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:51:17] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 19:51:18,313] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:51:18] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 19:51:18,350] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:51:18] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2022-12-29 19:51:18,359] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:51:18] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 19:51:30,352] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:51:30] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 19:51:30,390] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:51:30] "GET /static/style.css HTTP/1.1" 200 -
[2022-12-29 19:51:30,399] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:51:30] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 19:51:50,446] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:51:50] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 19:51:50,480] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:51:50] "GET /static/style.css HTTP/1.1" 200 -
[2022-12-29 19:51:50,486] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:51:50] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 19:52:04,581] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:52:04] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 19:52:04,622] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:52:04] "GET /static/style.css HTTP/1.1" 200 -
[2022-12-29 19:52:04,629] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:52:04] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 19:52:20,483] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:52:20] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 19:52:20,520] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:52:20] "GET /static/style.css HTTP/1.1" 200 -
[2022-12-29 19:52:20,526] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:52:20] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 19:52:34,542] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:52:34] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 19:52:34,656] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:52:34] "GET /static/style.css HTTP/1.1" 200 -
[2022-12-29 19:52:34,681] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:52:34] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 19:54:35,127] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:54:35] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 19:54:35,183] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:54:35] "GET /static/style.css HTTP/1.1" 200 -
[2022-12-29 19:54:35,200] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:54:35] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 19:56:16,740] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:56:16] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 19:56:16,775] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:56:16] "GET /static/style.css HTTP/1.1" 200 -
[2022-12-29 19:56:16,783] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:56:16] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 19:56:17,783] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:56:17] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 19:56:17,875] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:56:17] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2022-12-29 19:56:17,883] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:56:17] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 19:56:30,543] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:56:30] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 19:56:30,657] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:56:30] "GET /static/style.css HTTP/1.1" 200 -
[2022-12-29 19:56:30,678] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:56:30] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 19:56:31,501] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:56:31] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 19:56:31,549] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:56:31] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2022-12-29 19:56:31,556] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:56:31] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 19:56:38,077] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:56:38] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 19:56:38,131] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:56:38] "GET /static/style.css HTTP/1.1" 200 -
[2022-12-29 19:56:38,139] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:56:38] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 19:56:54,159] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:56:54] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 19:56:54,253] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:56:54] "GET /static/style.css HTTP/1.1" 200 -
[2022-12-29 19:56:54,260] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:56:54] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 19:57:01,745] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:57:01] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 19:57:01,780] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:57:01] "GET /static/style.css HTTP/1.1" 200 -
[2022-12-29 19:57:01,790] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:57:01] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 19:57:42,986] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:57:42] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 19:57:43,086] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:57:43] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2022-12-29 19:57:43,100] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:57:43] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 19:57:44,535] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:57:44] "GET /auth/register HTTP/1.1" 200 -
[2022-12-29 19:57:44,653] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:57:44] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2022-12-29 19:57:44,666] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:57:44] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 19:57:49,575] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:57:49] "[32mGET /employee/profile HTTP/1.1[0m" 302 -
[2022-12-29 19:57:49,588] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:57:49] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 19:57:49,631] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:57:49] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2022-12-29 19:57:49,638] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:57:49] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 19:57:54,796] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:57:54] "[32mPOST /auth/login HTTP/1.1[0m" 302 -
[2022-12-29 19:57:54,827] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:57:54] "GET /home HTTP/1.1" 200 -
[2022-12-29 19:57:54,863] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:57:54] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2022-12-29 19:57:54,870] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:57:54] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 19:59:03,230] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:59:03] "[32mGET /auth/logout HTTP/1.1[0m" 302 -
[2022-12-29 19:59:03,236] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:59:03] "[32mGET / HTTP/1.1[0m" 302 -
[2022-12-29 19:59:03,245] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:59:03] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 19:59:03,286] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:59:03] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2022-12-29 19:59:03,295] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:59:03] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 19:59:34,410] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:59:34] "GET /auth/register HTTP/1.1" 200 -
[2022-12-29 19:59:34,455] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:59:34] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2022-12-29 19:59:34,461] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 19:59:34] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 20:00:35,075] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:00:35] "[32mGET /employee/profile HTTP/1.1[0m" 302 -
[2022-12-29 20:00:35,085] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:00:35] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 20:00:35,119] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:00:35] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2022-12-29 20:00:35,126] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:00:35] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 20:02:53,964] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:02:53] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 20:02:54,028] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:02:54] "GET /static/style.css HTTP/1.1" 200 -
[2022-12-29 20:02:54,044] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:02:54] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 20:03:35,888] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:03:35] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 20:03:35,927] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:03:35] "GET /static/style.css HTTP/1.1" 200 -
[2022-12-29 20:03:35,934] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:03:35] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 20:03:45,607] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:03:45] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 20:03:45,641] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:03:45] "GET /static/style.css HTTP/1.1" 200 -
[2022-12-29 20:03:45,648] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:03:45] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 20:05:14,246] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:05:14] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 20:05:14,288] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:05:14] "GET /static/style.css HTTP/1.1" 200 -
[2022-12-29 20:05:14,295] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:05:14] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 20:05:27,547] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:05:27] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 20:05:27,584] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:05:27] "GET /static/style.css HTTP/1.1" 200 -
[2022-12-29 20:05:27,593] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:05:27] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 20:05:42,647] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:05:42] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 20:05:42,706] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:05:42] "GET /static/style.css HTTP/1.1" 200 -
[2022-12-29 20:05:42,722] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:05:42] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 20:05:56,017] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:05:56] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 20:05:56,058] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:05:56] "GET /static/style.css HTTP/1.1" 200 -
[2022-12-29 20:05:56,068] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:05:56] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 20:06:08,084] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:06:08] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 20:06:08,129] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:06:08] "GET /static/style.css HTTP/1.1" 200 -
[2022-12-29 20:06:08,134] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:06:08] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 20:06:17,157] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:06:17] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 20:06:17,257] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:06:17] "GET /static/style.css HTTP/1.1" 200 -
[2022-12-29 20:06:17,269] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:06:17] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 20:06:35,183] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:06:35] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 20:06:35,241] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:06:35] "GET /static/style.css HTTP/1.1" 200 -
[2022-12-29 20:06:35,255] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:06:35] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 20:06:44,782] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:06:44] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 20:06:44,890] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:06:44] "GET /static/style.css HTTP/1.1" 200 -
[2022-12-29 20:06:44,905] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:06:44] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 20:06:50,982] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:06:50] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 20:06:51,015] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:06:51] "GET /static/style.css HTTP/1.1" 200 -
[2022-12-29 20:06:51,022] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 20:06:51] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 22:23:47,932] INFO | setup >>> App started...
[2022-12-29 22:23:47,941] INFO | _internal >>> [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.229.196:5000
[2022-12-29 22:23:47,941] INFO | _internal >>> [33mPress CTRL+C to quit[0m
[2022-12-29 22:23:52,604] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 22:23:52] "[32mGET / HTTP/1.1[0m" 302 -
[2022-12-29 22:23:52,721] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 22:23:52] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 22:23:52,867] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 22:23:52] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2022-12-29 22:23:52,873] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 22:23:52] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 22:24:40,660] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 22:24:40] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[2022-12-29 22:25:03,081] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 22:25:03] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 22:25:03,121] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 22:25:03] "GET /static/style.css HTTP/1.1" 200 -
[2022-12-29 22:25:03,132] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 22:25:03] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 22:25:11,661] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 22:25:11] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 22:25:11,693] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 22:25:11] "GET /static/style.css HTTP/1.1" 200 -
[2022-12-29 22:25:11,700] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 22:25:11] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2022-12-29 22:28:21,707] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 22:28:21] "GET /auth/login HTTP/1.1" 200 -
[2022-12-29 22:28:21,747] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 22:28:21] "GET /static/style.css HTTP/1.1" 200 -
[2022-12-29 22:28:21,754] INFO | _internal >>> 127.0.0.1 - - [29/Dec/2022 22:28:21] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2023-01-13 12:43:50,904] INFO | setup >>> App started...
[2023-01-13 12:43:50,911] INFO | _internal >>> [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.151.173:5000
[2023-01-13 12:43:50,912] INFO | _internal >>> [33mPress CTRL+C to quit[0m
[2023-01-13 12:43:57,959] INFO | _internal >>> 127.0.0.1 - - [13/Jan/2023 12:43:57] "[32mGET / HTTP/1.1[0m" 302 -
[2023-01-13 12:43:58,343] INFO | _internal >>> 127.0.0.1 - - [13/Jan/2023 12:43:58] "GET /auth/login HTTP/1.1" 200 -
[2023-01-13 12:43:58,508] INFO | _internal >>> 127.0.0.1 - - [13/Jan/2023 12:43:58] "GET /static/alert.js HTTP/1.1" 200 -
[2023-01-13 12:43:58,545] INFO | _internal >>> 127.0.0.1 - - [13/Jan/2023 12:43:58] "GET /static/style.css HTTP/1.1" 200 -
[2023-01-13 12:44:02,369] INFO | _internal >>> 127.0.0.1 - - [13/Jan/2023 12:44:02] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[2023-01-13 12:44:23,692] INFO | _internal >>> 127.0.0.1 - - [13/Jan/2023 12:44:23] "GET /auth/register HTTP/1.1" 200 -
[2023-01-13 12:44:23,729] INFO | _internal >>> 127.0.0.1 - - [13/Jan/2023 12:44:23] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2023-01-13 12:44:23,739] INFO | _internal >>> 127.0.0.1 - - [13/Jan/2023 12:44:23] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2023-02-01 09:49:33,879] INFO | setup >>> App started...
[2023-02-01 09:49:33,896] INFO | _internal >>> [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://127.0.0.1:5000
[2023-02-01 09:49:33,896] INFO | _internal >>> [33mPress CTRL+C to quit[0m
[2023-02-01 09:49:44,927] INFO | _internal >>> 127.0.0.1 - - [01/Feb/2023 09:49:44] "[32mGET / HTTP/1.1[0m" 302 -
[2023-02-01 09:49:45,015] INFO | _internal >>> 127.0.0.1 - - [01/Feb/2023 09:49:45] "GET /auth/login HTTP/1.1" 200 -
[2023-02-01 09:49:45,241] INFO | _internal >>> 127.0.0.1 - - [01/Feb/2023 09:49:45] "GET /static/alert.js HTTP/1.1" 200 -
[2023-02-01 09:49:45,249] INFO | _internal >>> 127.0.0.1 - - [01/Feb/2023 09:49:45] "GET /static/style.css HTTP/1.1" 200 -
[2023-02-01 09:49:45,441] INFO | _internal >>> 127.0.0.1 - - [01/Feb/2023 09:49:45] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[2023-02-01 09:49:52,496] INFO | _internal >>> 127.0.0.1 - - [01/Feb/2023 09:49:52] "[32mGET /employee/profile HTTP/1.1[0m" 302 -
[2023-02-01 09:49:52,504] INFO | _internal >>> 127.0.0.1 - - [01/Feb/2023 09:49:52] "GET /auth/login HTTP/1.1" 200 -
[2023-02-01 09:49:52,544] INFO | _internal >>> 127.0.0.1 - - [01/Feb/2023 09:49:52] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2023-02-01 09:49:52,544] INFO | _internal >>> 127.0.0.1 - - [01/Feb/2023 09:49:52] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2023-02-01 09:49:54,685] INFO | _internal >>> 127.0.0.1 - - [01/Feb/2023 09:49:54] "[32mGET /employee HTTP/1.1[0m" 302 -
[2023-02-01 09:49:54,685] INFO | _internal >>> 127.0.0.1 - - [01/Feb/2023 09:49:54] "GET /auth/login HTTP/1.1" 200 -
[2023-02-01 09:49:54,717] INFO | _internal >>> 127.0.0.1 - - [01/Feb/2023 09:49:54] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2023-02-01 09:49:54,717] INFO | _internal >>> 127.0.0.1 - - [01/Feb/2023 09:49:54] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2023-02-01 09:49:55,164] INFO | _internal >>> 127.0.0.1 - - [01/Feb/2023 09:49:55] "GET /auth/login HTTP/1.1" 200 -
[2023-02-01 09:49:55,188] INFO | _internal >>> 127.0.0.1 - - [01/Feb/2023 09:49:55] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2023-02-01 09:49:55,188] INFO | _internal >>> 127.0.0.1 - - [01/Feb/2023 09:49:55] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2023-02-02 22:45:50,189] INFO | setup >>> App started...
[2023-02-02 22:45:50,209] INFO | _internal >>> [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.229.173:5000
[2023-02-02 22:45:50,209] INFO | _internal >>> [33mPress CTRL+C to quit[0m
[2023-02-02 22:45:56,820] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:45:56] "[32mGET / HTTP/1.1[0m" 302 -
[2023-02-02 22:45:56,911] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:45:56] "GET /auth/login HTTP/1.1" 200 -
[2023-02-02 22:45:57,062] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:45:57] "GET /static/alert.js HTTP/1.1" 200 -
[2023-02-02 22:45:57,072] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:45:57] "GET /static/style.css HTTP/1.1" 200 -
[2023-02-02 22:45:59,432] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:45:59] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[2023-02-02 22:46:25,229] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:46:25] "GET /auth/register HTTP/1.1" 200 -
[2023-02-02 22:46:25,268] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:46:25] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2023-02-02 22:46:25,282] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:46:25] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2023-02-02 22:46:31,322] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:46:31] "GET /auth/login HTTP/1.1" 200 -
[2023-02-02 22:46:31,371] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:46:31] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2023-02-02 22:46:31,380] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:46:31] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2023-02-02 22:46:35,363] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:46:35] "[32mGET /employee/profile HTTP/1.1[0m" 302 -
[2023-02-02 22:46:35,376] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:46:35] "GET /auth/login HTTP/1.1" 200 -
[2023-02-02 22:46:35,423] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:46:35] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2023-02-02 22:46:35,424] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:46:35] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2023-02-02 22:46:37,696] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:46:37] "[32mGET /employee HTTP/1.1[0m" 302 -
[2023-02-02 22:46:37,705] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:46:37] "GET /auth/login HTTP/1.1" 200 -
[2023-02-02 22:46:37,746] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:46:37] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2023-02-02 22:46:37,747] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:46:37] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2023-02-02 22:46:56,391] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:46:56] "[32mPOST /auth/login HTTP/1.1[0m" 302 -
[2023-02-02 22:46:56,410] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:46:56] "GET /home HTTP/1.1" 200 -
[2023-02-02 22:46:56,449] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:46:56] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2023-02-02 22:46:56,459] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:46:56] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2023-02-02 22:47:26,939] DEBUG | connectionpool >>> Starting new HTTP connection (1): api:5001
[2023-02-02 22:47:29,237] ERROR | app >>> Exception on /search [POST]
Traceback (most recent call last):
  File "C:\Users\sudhe\OneDrive\Desktop\Github\Employee Management App\Main App\env\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\sudhe\OneDrive\Desktop\Github\Employee Management App\Main App\env\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\sudhe\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sudhe\OneDrive\Desktop\Github\Employee Management App\Main App\env\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\sudhe\OneDrive\Desktop\Github\Employee Management App\Main App\env\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\sudhe\OneDrive\Desktop\Github\Employee Management App\Main App\env\lib\site-packages\urllib3\connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Users\sudhe\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\sudhe\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\sudhe\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\sudhe\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Users\sudhe\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Users\sudhe\OneDrive\Desktop\Github\Employee Management App\Main App\env\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "C:\Users\sudhe\OneDrive\Desktop\Github\Employee Management App\Main App\env\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000023EFE502620>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sudhe\OneDrive\Desktop\Github\Employee Management App\Main App\env\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\sudhe\OneDrive\Desktop\Github\Employee Management App\Main App\env\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\sudhe\OneDrive\Desktop\Github\Employee Management App\Main App\env\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='api', port=5001): Max retries exceeded with url: http://127.0.0.1:5001/hg (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023EFE502620>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sudhe\OneDrive\Desktop\Github\Employee Management App\Main App\env\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\sudhe\OneDrive\Desktop\Github\Employee Management App\Main App\env\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\sudhe\OneDrive\Desktop\Github\Employee Management App\Main App\env\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\sudhe\OneDrive\Desktop\Github\Employee Management App\Main App\env\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\sudhe\OneDrive\Desktop\Github\Employee Management App\Main App\flaskApp\auth.py", line 37, in wrapped_view
    return view(**kwargs)
  File "C:\Users\sudhe\OneDrive\Desktop\Github\Employee Management App\Main App\flaskApp\auth.py", line 48, in wrapped_view
    return view(**kwargs)
  File "C:\Users\sudhe\OneDrive\Desktop\Github\Employee Management App\Main App\flaskApp\engine.py", line 195, in search
    data_from_api = fetch_data_from_api(Searched)
  File "C:\Users\sudhe\OneDrive\Desktop\Github\Employee Management App\Main App\flaskApp\engine.py", line 209, in fetch_data_from_api
    data = requests.get("http://127.0.0.1:5001/"+url_data,proxies={"http": "http://api:5001/"}, verify=False)
  File "C:\Users\sudhe\OneDrive\Desktop\Github\Employee Management App\Main App\env\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\sudhe\OneDrive\Desktop\Github\Employee Management App\Main App\env\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\sudhe\OneDrive\Desktop\Github\Employee Management App\Main App\env\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\sudhe\OneDrive\Desktop\Github\Employee Management App\Main App\env\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\sudhe\OneDrive\Desktop\Github\Employee Management App\Main App\env\lib\site-packages\requests\adapters.py", line 559, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPConnectionPool(host='api', port=5001): Max retries exceeded with url: http://127.0.0.1:5001/hg (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023EFE502620>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')))
[2023-02-02 22:47:29,394] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:47:29] "[35m[1mPOST /search HTTP/1.1[0m" 500 -
[2023-02-02 22:47:43,588] INFO | engine >>> A user visited the home page >>> {'empId': 6}
[2023-02-02 22:47:43,634] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:47:43] "GET /employee HTTP/1.1" 200 -
[2023-02-02 22:47:43,676] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:47:43] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2023-02-02 22:47:43,694] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:47:43] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2023-02-02 22:47:52,414] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:47:52] "GET /employee/profile HTTP/1.1" 200 -
[2023-02-02 22:47:52,463] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:47:52] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2023-02-02 22:47:52,484] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:47:52] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2023-02-02 22:48:07,454] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:48:07] "GET /auth/register HTTP/1.1" 200 -
[2023-02-02 22:48:07,499] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:48:07] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2023-02-02 22:48:07,511] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:48:07] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2023-02-02 22:48:10,367] INFO | engine >>> A user visited the home page >>> {'empId': 6}
[2023-02-02 22:48:10,376] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:48:10] "GET /employee HTTP/1.1" 200 -
[2023-02-02 22:48:10,423] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:48:10] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2023-02-02 22:48:10,431] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:48:10] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2023-02-02 22:48:14,327] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:48:14] "GET /auth/register HTTP/1.1" 200 -
[2023-02-02 22:48:14,379] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:48:14] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2023-02-02 22:48:14,390] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:48:14] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2023-02-02 22:48:16,056] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:48:16] "[32mGET /auth/logout HTTP/1.1[0m" 302 -
[2023-02-02 22:48:16,062] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:48:16] "[32mGET / HTTP/1.1[0m" 302 -
[2023-02-02 22:48:16,078] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:48:16] "GET /auth/login HTTP/1.1" 200 -
[2023-02-02 22:48:16,133] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:48:16] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2023-02-02 22:48:16,157] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:48:16] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2023-02-02 22:51:06,419] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:51:06] "GET /auth/register HTTP/1.1" 200 -
[2023-02-02 22:51:06,465] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:51:06] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2023-02-02 22:51:06,474] INFO | _internal >>> 127.0.0.1 - - [02/Feb/2023 22:51:06] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2023-02-16 19:30:33,273] INFO | setup >>> App started...
[2023-02-16 19:30:33,286] INFO | _internal >>> [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.47.173:5000
[2023-02-16 19:30:33,286] INFO | _internal >>> [33mPress CTRL+C to quit[0m
[2023-02-16 19:30:37,041] INFO | _internal >>> 127.0.0.1 - - [16/Feb/2023 19:30:37] "[32mGET / HTTP/1.1[0m" 302 -
[2023-02-16 19:30:37,169] INFO | _internal >>> 127.0.0.1 - - [16/Feb/2023 19:30:37] "GET /auth/login HTTP/1.1" 200 -
[2023-02-16 19:30:37,313] INFO | _internal >>> 127.0.0.1 - - [16/Feb/2023 19:30:37] "GET /static/alert.js HTTP/1.1" 200 -
[2023-02-16 19:30:37,313] INFO | _internal >>> 127.0.0.1 - - [16/Feb/2023 19:30:37] "GET /static/style.css HTTP/1.1" 200 -
[2023-02-16 19:30:47,870] INFO | _internal >>> 127.0.0.1 - - [16/Feb/2023 19:30:47] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[2023-02-16 19:31:02,958] INFO | _internal >>> 127.0.0.1 - - [16/Feb/2023 19:31:02] "GET /auth/login HTTP/1.1" 200 -
[2023-02-16 19:31:02,983] INFO | _internal >>> 127.0.0.1 - - [16/Feb/2023 19:31:02] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2023-02-16 19:31:02,983] INFO | _internal >>> 127.0.0.1 - - [16/Feb/2023 19:31:02] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2023-02-16 19:31:05,366] INFO | _internal >>> 127.0.0.1 - - [16/Feb/2023 19:31:05] "GET /auth/login HTTP/1.1" 200 -
[2023-02-16 19:31:05,382] INFO | _internal >>> 127.0.0.1 - - [16/Feb/2023 19:31:05] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2023-02-16 19:31:05,390] INFO | _internal >>> 127.0.0.1 - - [16/Feb/2023 19:31:05] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2023-02-16 19:31:09,545] INFO | setup >>> App started...
[2023-02-16 19:31:09,545] INFO | _internal >>> [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.47.173:5000
[2023-02-16 19:31:09,545] INFO | _internal >>> [33mPress CTRL+C to quit[0m
[2023-02-16 19:31:11,957] INFO | _internal >>> 127.0.0.1 - - [16/Feb/2023 19:31:11] "GET /auth/login HTTP/1.1" 200 -
[2023-02-16 19:31:12,045] INFO | _internal >>> 127.0.0.1 - - [16/Feb/2023 19:31:12] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
[2023-02-16 19:31:12,045] INFO | _internal >>> 127.0.0.1 - - [16/Feb/2023 19:31:12] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2023-02-16 19:31:34,134] INFO | _internal >>> 127.0.0.1 - - [16/Feb/2023 19:31:34] "GET /auth/register HTTP/1.1" 200 -
[2023-02-16 19:31:34,158] INFO | _internal >>> 127.0.0.1 - - [16/Feb/2023 19:31:34] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2023-02-16 19:31:34,158] INFO | _internal >>> 127.0.0.1 - - [16/Feb/2023 19:31:34] "[36mGET /static/alert.js HTTP/1.1[0m" 304 -
